config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :products do
    resources :reviews
  end
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews, dependent: :destroy
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
  )}
  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :made_in_the_usa, -> { where("country_of_origin like ?", "%United States%")}
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)

  private

  def titleize_product
    self.name = self.name.titleize
  end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :product
  validates :title, presence: true
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, minimum: 50
  validates_length_of :content_body, maximum: 250
  
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :password
  validates_confirmation_of :password
  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize

  def index
    @products = Product.all
    if params[:three_most_recent]
      @products = Product.three_most_recent
    elsif params[:most_reviews]
      @products = Product.most_reviews
    elsif params[:made_in_the_usa]
      @products = Product.made_in_the_usa
    end
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "#{@product.name} was successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "#{@product.name} was successfully deleted!"
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authorize

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "#{@review.title} was successfully saved!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "#{@review.title} was successfully deleted!"
    redirect_to product_path(@review.product)
  end

  private

  def review_params
    params.require(:review).permit(:title, :author, :content_body, :rating)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "Welcome back, #{@user.username}! You've successfully signed in."
      session[:user_id] = @user.id
      redirect_to "/products"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've successfully signed out."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome, #{@user.username}! You've successfully signed up."
      session[:user_id] = @user.id
      redirect_to "/products"
    else
      flash[:alert] = "There was a problem signing up. Please try again."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning custom-alert" role="alert">
    <p>Please fix these errors:</p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<% country_list = [
"Select a country",
"Afghanistan",
"Aland Islands",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua And Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Bosnia and Herzegowina",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory",
"Brunei Darussalam",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Cocos (Keeling) Islands",
"Colombia",
"Comoros",
"Congo",
"Congo, the Democratic Republic of the",
"Cook Islands",
"Costa Rica",
"Cote d'Ivoire",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Falkland Islands (Malvinas)",
"Faroe Islands",
"Fiji",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"French Southern Territories",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Heard and McDonald Islands",
"Holy See (Vatican City State)",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran, Islamic Republic of",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jersey",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea, Democratic People's Republic of",
"Korea, Republic of",
"Kuwait",
"Kyrgyzstan",
"Lao People's Democratic Republic",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libyan Arab Jamahiriya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macao",
"Macedonia, The Former Yugoslav Republic Of",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Micronesia, Federated States of",
"Moldova, Republic of",
"Monaco",
"Mongolia",
"Montenegro",
"Montserrat",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Palestinian Territory, Occupied",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russian Federation",
"Rwanda",
"Saint Barthelemy",
"Saint Helena",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Pierre and Miquelon",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Georgia and the South Sandwich Islands",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard and Jan Mayen",
"Swaziland",
"Sweden",
"Switzerland",
"Syrian Arab Republic",
"Taiwan, Province of China",
"Tajikistan",
"Tanzania, United Republic of",
"Thailand",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks and Caicos Islands",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"United States Minor Outlying Islands",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Viet Nam",
"Virgin Islands, British",
"Virgin Islands, U.S.",
"Wallis and Futuna",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe"
] %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.label :cost %>
  <div class="form-group">
    <%= f.number_field :cost, class: "form-control" %>
  </div>
  <%= f.label :country_of_origin %>
  <div class="form-group">
    <%= f.select :country_of_origin, options_for_select(country_list, selected: "Select a country", disabled: "Select a country"), {}, {:class => "form-control"} %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :title %>
  <div class="form-group">
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <%= f.label :author %>
  <div class="form-group">
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <%= f.label :content_body %>
  <div class="form-group">
    <%= f.text_area :content_body, class: "form-control" %>
  </div>
  <%= f.label :rating %>
  <div class="form-group">
    <%= range_field(:review, :rating, in: 1..5, value: "1", step: "1", class: "form-control") %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario's Specialty Food Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Mario's Specialty Food Products</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if current_user %>
            <%= link_to "Sign Out", '/signout', class: "nav-item nav-link" %>
          <% else %>
            <%= link_to "Sign In", '/signin', class: "nav-item nav-link" %>
            <%= link_to "Sign Up", 'signup', class: "nav-item nav-link" %>
          <% end %>
        </div>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <% if flash[:alert] %>
        <%= content_tag :div, msg, class: "alert alert-warning", role: "alert" %>
      <% else %>
        <%= content_tag :div, msg, class: "alert alert-success", role: "notice" %>
      <% end %>
    <% end %>
    <div class="container">
      <% if current_user %>
        <p>
          You are signed in as <%= current_user.username %>.
          <% if current_user.admin == true %>
            <span class="badge badge-pill badge-info">Admin</span>
          <% end %>
        </p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %>:</h1>

<%= render "layouts/product_form" %>

<hr>

<a><%= link_to "Return to product", product_path %></a>

app/views/products/index.html.erb
<h1>Products</h1>

<% if current_user.admin == true %>
  <p>Don't see what you're looking for? <%= link_to "Add a product here", new_product_path %>.</p>
<% end %>

<% if @products.any? %>
  <form>
    <div class="form-group">
      <button class="btn btn-secondary" type="submit" name="three_most_recent">Three Most Recent</button>
      <button class="btn btn-secondary" type="submit" name="most_reviews">Most Reviews</button>
      <button class="btn btn-secondary" type="submit" name="made_in_the_usa">Made in the USA</button>
      <a><%= link_to "Remove filters", products_path, role: "button", class: "btn btn-outline-secondary" %></a>
    </div>
  </form>
  <ul>
    <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are <%= @products.count %> products to display.</p>
<% end %>

app/views/products/new.html.erb
<h1>Add a product:</h1>

<%= render "layouts/product_form" %>

<hr>

<a><%= link_to "Return to products", products_path %></a>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2><strong>$<%= @product.cost %></strong>, <%= @product.country_of_origin %></h2>
<p>What do you think of <%= @product.name %>? <%= link_to "Write a review here", new_product_review_path(@product) %>.</p>

<% if @product.reviews.any? %>
  <p>Here are the reviews for <%= @product.name %>:</p>
  <ul>
    <% @product.reviews.each do |review| %>
    <li>
      <%= link_to review.title, product_review_path(@product, review) %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>There are <%= @product.reviews.count %> reviews listed for <%= @product.name %>.</p>
<% end %>

<% if current_user.admin == true %>
  <a><%= link_to "Edit", edit_product_path(@product) %></a>  |
  <a><%= link_to "Delete", product_path(@product),
    :data => {:confirm => "You sure?",
    :method => "delete"} %></a>
<% end %>

<hr>

<a><%= link_to "Return to products", products_path %></a>

app/views/reviews/edit.html.erb
<h1>Edit <%= @review.title %>:</h1>

<%= render "layouts/review_form" %>

<hr>

<a><%= link_to "Return to #{@product.name}", product_path(@product) %></a>

app/views/reviews/new.html.erb
<h1>Write a review:</h1>

<%= render "layouts/review_form" %>

<hr>

<a><%= link_to "Return to #{@product.name}", product_path(@product) %></a>

app/views/reviews/show.html.erb
<% x = 0 %>
<% stars = [] %>
<% until (x >= @review.rating) %>
  <% x += 1 %>
  <% stars.push('⭐️') %>
<% end %>
<h1><%= @review.title %></h1>
<h2><%= stars.join(" ") %></h2>
<h2><%= @review.author %></h2>
<p><%= @review.content_body %></p>

<% if current_user.admin == true %>
  <a><%= link_to "Edit", edit_product_review_path(@product, @review) %></a>  |  <a><%= link_to "Delete", product_review_path(@product, @review),
    :data => {:confirm => "Are you sure?",
    :method => "delete"} %></a>
<% end %>

<hr>

<a><%= link_to "Return to #{@product.name}", product_path(@product) %></a>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Already have an account? <%= link_to "Sign in here", 'signin' %>.</p>

<%= form_for @user do |f| %>
  <%= f.label "Username" %>
  <div class="form-group">
    <%= f.text_field :username %>
  </div>
  <%= f.label "Email" %>
  <div class="form-group">
    <%= f.text_field :email %>
  </div>
  <%= f.label "Password" %>
  <div class="form-group">
    <%= f.password_field :password %>
  </div>
  <%= f.label :password_confirmation %>
  <div class="form-group">
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= f.label :admin %>:
    <%= f.check_box :admin, checked_value: true, unchecked_value: false %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>